# Action for quality assurance (checking code with ESLint for the time being)
name: Quality Assurance

# Trigger workflow on pushes to master including Javascript files and any pull requests for master
on:
  push:
    branches: [ master ]
    paths:    [ "**.js" ]
  pull_request:
    branches: [ master ]

# Workflow
jobs:
  # Quality assurance job
  quality-assurance:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - name: Install modules
        run: npm install
      - name: Run code linter
        run: npm run lint