# Action for checking code with ESLint on pull requests
name: Lint

# Triggers
on:
  pull_request:
    branches: [ master ]

# Workflow
jobs:
  # Lint job
  eslint:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: ESLint Action
        uses: hallee/eslint-action@1.0.3
